hoho00/master -> euphony-io/master add codeowners file
euphony-io/check-in-speaker pull request #11
Opened 2021-09-25 05:52 UTC by hoho00

add codeowners file

2021-09-25 06:10 UTC, jopopcorn approved these changes
잘하셨습니다!

2021-09-25 08:45 UTC, jopopcorn approved these changes
다음부터는 이슈마다 링크할 수 있도록 브랜치별로 나누어서 PR을 올리시면 좋을 것 같습니다!
ex) pr_template, issue_template 브랜치로 나누어서 PR template과 issue template의 PR을 따로따로 생성

2021-09-25 08:47 UTC, hoho00 commented
@jopopcorn 엇 감사합니다. 다음 부터는 그렇게 올릴게요. 지적 감사합니다 :)

2021-09-25 08:53 UTC, psh2849 approved these changes
수고하셨습니다~~~

2021-09-25 10:18 UTC, HACore requested changes
수고하셨습니다!

그런데 CODEOWNERS를 팀으로 설정하기 전에 확인하고 싶은 부분이 있는데, 혹시 euphoria팀이 이 저장소에서 쓰기권한을 가지고 있나요?
Team code owner에 대한 가이드가 적힌 [(About code owners)](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners)를 보시면, 다음과 같이 안내되고 있습니다.
> When the code owner is a team, that team must have explicit `write` permissions, even if all the individual members of the team already have `write` permissions directly, through organization membership.

_**Settings > Manage access**_ 에서 'euphoria' 팀에 `write` 이상의 명시적 권한이 주어져있는지 @jopopcorn님에게 확인 부탁드려도 될까요?
저는 해당 내용을 확인할 수가 없네요😂

2021-09-25 10:48 UTC, hoho00 commented on CODEOWNERS
> +// the euphony-co team in the euphony-io organization owns everything in this repository
감사합니다

2021-09-25 10:55 UTC, jopopcorn commented on CODEOWNERS
> +// the euphony-co team in the euphony-io organization owns everything in this repository
현재 maintain 권한이어서 쓰기권한은 있습니다! 꼼꼼하게 확인해주셨네요!

2021-09-27 15:24 UTC, jopopcorn commented
@hoho00 머지를 하지 않고 close를 하셨는데 병합해주셔야 템플릿이 적용됩니다!

2021-09-27 15:24 UTC, merged