README 작성
euphony-io/check-in-speaker pull request #35
Opened 2021-10-07 18:55 UTC by HACore

- 앱에 대한 소개와 간략한 기능 소개
- 앱이 만들어진 배경 1. QR 코드의 불편한 점을 보완 2. 유명무실한 안심번호를 활용
- 앱 실행 방법 (스크린샷과 함께)
- issue 리포트 방법
- 라이센스 고지

잘못된 부분이 있거나 좀 더 보충할 내용이 필요하다면 리뷰 부탁드립니다! 😄

2021-10-08 04:20 UTC, jopopcorn requested changes
잘 작성해주셨네요!! 제가 보기엔 충분해보입니다!
대신 커밋을 하나로 합쳐서 올려주시면 더 좋을 것 같아요!
`git squash`를 활용해서 커밋을 하나로 합친 후 병합해주심 됩니다!!
많이 바쁘신 것 같은데 고생 많으셨습니다 😿

2021-10-08 04:44 UTC, psh2849 approved these changes
확인했습니다 잘하신 것 같아요 ㅎㅎ
고생하셨습니다 👍 👍

2021-10-08 06:57 UTC, psh2849 commented on README.md
> +<br>`체크인 종료` 버튼을 통해 언제든지 음파 통신을 멈출 수 있으며 데이터 전송이 완료되면 자동으로 체크인이 종료됩니다.
이 부분에서 `데이터 전송이 완료되면 자동으로 체크인이 종료됩니다.`는 송신측에서 종료 됐음을 알 수 있는 기능이 따로 없기 때문에 아직 구현이 안된 상태에요 ㅠㅠ 따라서 이 부분은 삭제 해주시면 감사하겠습니다!

2021-10-08 13:28 UTC, HACore commented on README.md
> +<br>`체크인 종료` 버튼을 통해 언제든지 음파 통신을 멈출 수 있으며 데이터 전송이 완료되면 자동으로 체크인이 종료됩니다.
아 그랬군요ㅠㅠ 넵 수정해서 머지하겠습니다!

2021-10-08 14:31 UTC, kmsaidev approved these changes
고생하셨습니다!!👍👍

2021-10-08 16:39 UTC, jopopcorn approved these changes
수정사항 확인했습니다 고생 많으셨습니다!!

2021-10-09 09:22 UTC, hoho00 approved these changes

2021-10-09 09:57 UTC, merged